[package]
name = "swarm-simulation"
version = "0.1.0"
edition = "2024"

[dependencies]
glam = "0.27"
macroquad = "0.4.14"
rand = "0.9.2"
rand_xoshiro = "0.7.0"
getrandom = { version = "0.3.4", features = ["wasm_js"] }
macroquad-viewplane-camera = "0.1.0"
